import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 20,

    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    borderTopRightRadius: 20,
    borderTopLeftRadius: 20,
    borderBottomColor: "#f0f0f0",
    borderBottomWidth: 1,
  },
  headerLeft: {
    flex: 1,
  },
  gameTitle: {
    fontSize: 24,
    fontWeight: "bold",
    color: "#333",
  },
  exitButton: {
    backgroundColor: "#f44336",
    width: 36,
    height: 36,
    borderRadius: 18,
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#f44336",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 4,
  },
  exitButtonText: {
    color: "white",
    fontSize: 18,
    fontWeight: "bold",
  },
  gameContent: {
    flex: 1,
    padding: 20,
    alignItems: "center",
    justifyContent: "center",
  },
  playerInfo: {
    fontSize: 16,
    color: "#666",
    marginBottom: 5,
  },
  currentPlayer: {
    fontSize: 32,
    fontWeight: "bold",
    color: "#2196F3",
    marginBottom: 30,
    textAlign: "center",
  },
  timerContainer: {
    alignItems: "center",
    marginBottom: 50,
    backgroundColor: "white",
    padding: 30,
    borderRadius: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 5,
    width: "100%",
    maxWidth: 300,
  },
  timerDisplay: {
    fontSize: 48,
    fontWeight: "bold",
    color: "#333",
    fontFamily: "monospace",
  },

  targetTime: {
    fontSize: 16,
    color: "#666",
    marginTop: 10,
  },
  gameControls: {
    alignItems: "center",
    minHeight: 80,
  },
  readyButton: {
    backgroundColor: "#FF9800",
    paddingVertical: 15,
    paddingHorizontal: 40,
    borderRadius: 25,
  },
  readyButtonText: {
    color: "white",
    fontSize: 18,
    fontWeight: "bold",
  },
  startTimerButton: {
    backgroundColor: "#4CAF50",
    paddingVertical: 20,
    paddingHorizontal: 50,
    borderRadius: 30,
  },
  startTimerButtonText: {
    color: "white",
    fontSize: 20,
    fontWeight: "bold",
  },
  stopButton: {
    backgroundColor: "#f44336",
    paddingVertical: 25,
    paddingHorizontal: 60,
    borderRadius: 35,
    shadowColor: "#f44336",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  stopButtonText: {
    color: "white",
    fontSize: 24,
    fontWeight: "bold",
  },
  nextPlayerButton: {
    backgroundColor: "#4CAF50",
    paddingVertical: 20,
    paddingHorizontal: 50,
    borderRadius: 25,
    shadowColor: "#4CAF50",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  nextPlayerButtonText: {
    color: "white",
    fontSize: 20,
    fontWeight: "bold",
  },
  completedContainer: {
    alignItems: "center",
    padding: 20,
  },
  completedText: {
    fontSize: 24,
    fontWeight: "bold",
    color: "#4CAF50",
    textAlign: "center",
    marginBottom: 10,
  },
  completedSubText: {
    fontSize: 16,
    color: "#666",
    textAlign: "center",
  },
  viewResultsButton: {
    backgroundColor: "#2196F3",
    paddingVertical: 15,
    paddingHorizontal: 40,
    borderRadius: 25,
    marginTop: 15,
    shadowColor: "#2196F3",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  viewResultsButtonText: {
    color: "white",
    fontSize: 18,
    fontWeight: "bold",
    textAlign: "center",
  },
  hiddenTimeDisplay: {
    color: "#bbb", // or use 'transparent' if you want to hide completely
  },
});
