import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    marginBottom: 25,
  },
  inputContainer: {
    backgroundColor: "#ffffff",
    borderRadius: 16,
    padding: 20,
    shadowColor: "#9e35e5",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 3,
  },
  topicInput: {
    backgroundColor: "#f8f9fa",
    borderWidth: 2,
    borderColor: "#e9ecef",
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 12,
    fontSize: 16,
    color: "#343a40",
    marginBottom: 15,
  },
  confirmButton: {
    backgroundColor: "#9e35e5",
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 20,
    alignItems: "center",
    shadowColor: "#9e35e5",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.2,
    shadowRadius: 5,
    elevation: 3,
  },
  confirmButtonText: {
    color: "#ffffff",
    fontSize: 16,
    fontWeight: "600",
  },
  presetContainer: {
    marginTop: 20,
  },
  presetTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: "#9e35e5",
    marginBottom: 5,
  },
  presetHint: {
    fontSize: 14,
    color: "#6b7280",
    marginBottom: 15,
  },
  categoryContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  categoryTag: {
    backgroundColor: "#f3f4f6",
    borderRadius: 20,
    paddingHorizontal: 16,
    paddingVertical: 8,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: "#e5e7eb",
  },
  categoryText: {
    color: "#374151",
    fontSize: 14,
    fontWeight: "500",
  },
  topicDisplay: {
    backgroundColor: "#ffffff",
    borderRadius: 16,
    padding: 20,
    shadowColor: "#9e35e5",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 3,
    borderWidth: 2,
    borderColor: "#9e35e5",
    position: "relative",
  },
  topicText: {
    fontSize: 16,
    fontWeight: "600",
    color: "#9e35e5",
    marginBottom: 5,
  },
  editHint: {
    fontSize: 12,
    color: "#6b7280",
    fontStyle: "italic",
  },
  editButton: {
    position: "absolute",
    top: 15,
    right: 15,
    backgroundColor: "#f3f4f6",
    borderRadius: 20,
    width: 32,
    height: 32,
    alignItems: "center",
    justifyContent: "center",
  },
  editButtonText: {
    fontSize: 14,
  },
  preview: {
    fontSize: 14,
    color: "#6b46c1",
    fontStyle: "italic",
    marginTop: 5,
  },
});
