import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#f8f4ff", // 淺紫色背景
  },
  scrollContainer: {
    flexGrow: 1,
    padding: 20,
  },
  header: {
    alignItems: "center",
    marginBottom: 30,
    paddingTop: 20,
  },
  backButton: {
    position: "absolute",
    left: 0,
    top: 20,
    padding: 10,
    backgroundColor: "#ffffff",
    borderRadius: 12,
    shadowColor: "#9e35e5",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  backButtonText: {
    color: "#9e35e5",
    fontSize: 16,
    fontWeight: "600",
  },
  title: {
    fontSize: 32,
    fontWeight: "bold",
    color: "#9e35e5", // 主紫色
    marginBottom: 8,
    textAlign: "center",
  },
  subtitle: {
    fontSize: 16,
    color: "#6b46c1", // 深紫色
    textAlign: "center",
    opacity: 0.8,
  },
  topicPreview: {
    fontSize: 14,
    color: "#6b46c1",
    textAlign: "center",
    fontStyle: "italic",
    marginTop: 5,
  },
  optionsCount: {
    fontSize: 14,
    color: "#9e35e5",
    fontWeight: "600",
    textAlign: "center",
    marginTop: 10,
  },
  hint: {
    fontSize: 14,
    color: "#6b7280",
    textAlign: "center",
    marginBottom: 15,
    fontStyle: "italic",
  },
  optionRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 12,
    gap: 10,
  },
  optionsInput: {
    backgroundColor: "#ffffff",
    borderWidth: 2,
    borderColor: "#d1d5db",
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 12,
    fontSize: 16,
    color: "#1f2937",
    shadowColor: "#9e35e5",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  removeButton: {
    backgroundColor: "#ef4444",
    borderRadius: 20,
    width: 36,
    height: 36,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#ef4444",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
    elevation: 2,
  },
  removeButtonText: {
    color: "#ffffff",
    fontSize: 16,
    fontWeight: "bold",
  },
  addButton: {
    backgroundColor: "#9e35e5",
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 20,
    alignItems: "center",
    marginTop: 10,
    shadowColor: "#9e35e5",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.2,
    shadowRadius: 5,
    elevation: 3,
  },
  addButtonText: {
    color: "#ffffff",
    fontSize: 16,
    fontWeight: "600",
  },
  presetOptionsContainer: {
    marginTop: 30,
    backgroundColor: "#ffffff",
    borderRadius: 16,
    padding: 20,
    shadowColor: "#9e35e5",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 3,
  },
  presetOptionsTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: "#9e35e5",
    marginBottom: 8,
  },
  presetOptionsHint: {
    fontSize: 14,
    color: "#6b7280",
    marginBottom: 15,
  },
  presetOptionsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  presetOptionTag: {
    backgroundColor: "#f3f4f6",
    borderRadius: 20,
    paddingHorizontal: 16,
    paddingVertical: 8,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: "#e5e7eb",
  },
  presetOptionText: {
    color: "#374151",
    fontSize: 14,
    fontWeight: "500",
  },
  presetOptionTextActive: {
    color: "#9e35e5",
    fontWeight: "600",
  },
  resultContainer: {
    marginTop: 30,
    backgroundColor: "#ffffff",
    borderRadius: 20,
    padding: 25,
    shadowColor: "#9e35e5",
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 5,
    borderWidth: 2,
    borderColor: "#9e35e5",
    alignItems: "center",
  },

  resultTitle: {
    fontSize: 20,
    fontWeight: "700",
    color: "#9e35e5",
    marginBottom: 20,
    textAlign: "center",
  },

  resultBox: {
    backgroundColor: "#f8f5ff",
    borderRadius: 16,
    paddingVertical: 20,
    paddingHorizontal: 30,
    marginBottom: 25,
    borderWidth: 2,
    borderColor: "#e0d4f7",
    minWidth: "80%",
    alignItems: "center",
  },

  resultText: {
    fontSize: 24,
    fontWeight: "600",
    color: "#6b46c1",
    textAlign: "center",
    letterSpacing: 0.5,
  },

  resetButton: {
    backgroundColor: "#9e35e5",
    borderRadius: 25,
    paddingVertical: 12,
    paddingHorizontal: 30,
    shadowColor: "#9e35e5",
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 4,
  },

  resetButtonText: {
    color: "#ffffff",
    fontSize: 16,
    fontWeight: "600",
    textAlign: "center",
  },
});
