import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#f8f4ff", // 淺紫色背景
  },
  keyboardAvoidingView: {
    flex: 1,
  },
  scrollContainer: {
    flexGrow: 1,
    padding: 20,
    paddingTop: 10, // 減少頂部間距，因為 header 現在是固定的
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingVertical: 16,
    paddingTop: 20, // 給狀態欄留空間
    backgroundColor: "#f8f4ff", // 與背景色一致
    borderBottomWidth: 1,
    borderBottomColor: "rgba(158, 53, 229, 0.15)",
    shadowColor: "#9e35e5",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 4,
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "rgba(158, 53, 229, 0.1)",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(158, 53, 229, 0.2)",
  },
  backButtonText: {
    color: "#9e35e5",
    fontSize: 18,
    fontWeight: "700",
    marginLeft: -1, // 微調箭頭位置
  },
  title: {
    fontSize: 20,
    fontWeight: "700",
    color: "#9e35e5",
    textAlign: "center",
    flex: 1,
    marginHorizontal: 16,
  },
  headerRightSpace: {
    width: 40, // 與 backButton 同寬，保持平衡
  },
  titleContainer: {
    flex: 1,
    alignItems: "center",
  },
  subtitle: {
    fontSize: 12,
    color: "#9e35e5",
    opacity: 0.7,
    marginTop: 2,
    fontWeight: "500",
  },

  hint: {
    fontSize: 14,
    color: "#6b7280",
    textAlign: "center",
    marginBottom: 15,
    fontStyle: "italic",
  },
  optionRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 12,
    gap: 10,
  },
  removeButton: {
    backgroundColor: "#ef4444",
    borderRadius: 20,
    width: 36,
    height: 36,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#ef4444",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
    elevation: 2,
  },
  removeButtonText: {
    color: "#ffffff",
    fontSize: 16,
    fontWeight: "bold",
  },
  addButton: {
    backgroundColor: "#9e35e5",
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 20,
    alignItems: "center",
    marginTop: 10,
    shadowColor: "#9e35e5",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.2,
    shadowRadius: 5,
    elevation: 3,
  },
  addButtonText: {
    color: "#ffffff",
    fontSize: 16,
    fontWeight: "600",
  },
  resultContainer: {
    marginTop: 30,
    backgroundColor: "#ffffff",
    borderRadius: 20,
    padding: 25,
    shadowColor: "#9e35e5",
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 5,
    borderWidth: 2,
    borderColor: "#9e35e5",
    alignItems: "center",
  },

  resultTitle: {
    fontSize: 20,
    fontWeight: "700",
    color: "#9e35e5",
    marginBottom: 20,
    textAlign: "center",
  },

  resultBox: {
    backgroundColor: "#f8f5ff",
    borderRadius: 16,
    paddingVertical: 20,
    paddingHorizontal: 30,
    marginBottom: 25,
    borderWidth: 2,
    borderColor: "#e0d4f7",
    minWidth: "80%",
    alignItems: "center",
  },

  resultText: {
    fontSize: 24,
    fontWeight: "600",
    color: "#6b46c1",
    textAlign: "center",
    letterSpacing: 0.5,
  },

  resetButton: {
    backgroundColor: "#9e35e5",
    borderRadius: 25,
    paddingVertical: 12,
    paddingHorizontal: 30,
    shadowColor: "#9e35e5",
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 4,
  },
  resetButtonText: {
    color: "#ffffff",
    fontSize: 16,
    fontWeight: "600",
    textAlign: "center",
  },
  // 新增的樣式
  topicSection: {
    marginTop: 20,
    marginBottom: 0,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: "#9e35e5",
    marginBottom: 12,
    textAlign: "left",
  },
  // 新的選項按鈕樣式
  optionsSection: {
    marginBottom: 20,
  },
  optionsButton: {
    backgroundColor: "#ffffff",
    borderRadius: 16,
    padding: 20,
    shadowColor: "#9e35e5",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 3,
    borderWidth: 1,
    borderColor: "#e5e7eb",
  },
  optionsButtonContent: {
    flexDirection: "row",
    alignItems: "center",
  },
  optionsButtonIcon: {
    fontSize: 24,
    marginRight: 16,
  },
  optionsButtonTextContainer: {
    flex: 1,
  },
  optionsButtonTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: "#9e35e5",
    marginBottom: 4,
  },
  optionsButtonSubtitle: {
    fontSize: 14,
    color: "#6b7280",
  },
  optionsButtonArrow: {
    fontSize: 24,
    color: "#9e35e5",
    fontWeight: "300",
  },
  // 輪盤占位符樣式
  wheelPlaceholder: {
    backgroundColor: "#ffffff",
    borderRadius: 16,
    padding: 40,
    marginBottom: 20,
    alignItems: "center",
    shadowColor: "#9e35e5",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
    borderWidth: 2,
    borderColor: "#f3f4f6",
    borderStyle: "dashed",
  },
  wheelPlaceholderText: {
    fontSize: 18,
    fontWeight: "600",
    color: "#9e35e5",
    textAlign: "center",
    marginBottom: 8,
  },
  wheelPlaceholderHint: {
    fontSize: 14,
    color: "#6b7280",
    textAlign: "center",
    lineHeight: 20,
  },
  // Result Popup Modal Styles
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
  resultPopup: {
    backgroundColor: "#ffffff",
    borderRadius: 24,
    padding: 30,
    shadowColor: "#9e35e5",
    shadowOffset: {
      width: 0,
      height: 8,
    },
    shadowOpacity: 0.25,
    shadowRadius: 20,
    elevation: 10,
    borderWidth: 3,
    borderColor: "#9e35e5",
    alignItems: "center",
    maxWidth: "90%",
    minWidth: "80%",
  },
  resultPopupTitle: {
    fontSize: 24,
    fontWeight: "700",
    color: "#9e35e5",
    marginBottom: 20,
    textAlign: "center",
  },
  resultPopupBox: {
    backgroundColor: "#f8f5ff",
    borderRadius: 20,
    paddingVertical: 25,
    paddingHorizontal: 35,
    marginBottom: 30,
    borderWidth: 2,
    borderColor: "#e0d4f7",
    minWidth: "100%",
    alignItems: "center",
  },
  resultPopupText: {
    fontSize: 28,
    fontWeight: "700",
    color: "#6b46c1",
    textAlign: "center",
    letterSpacing: 0.5,
  },
  resultPopupButtons: {
    flexDirection: "row",
    gap: 15,
    width: "100%",
  },
  resultPopupButton: {
    flexDirection: "row",
    flex: 1,
    backgroundColor: "#9e35e5",
    borderRadius: 20,
    paddingVertical: 15,
    paddingHorizontal: 20,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#9e35e5",
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.2,
    shadowRadius: 6,
    elevation: 3,
  },
  resultPopupButtonText: {
    color: "#ffffff",
    fontSize: 16,
    fontWeight: "600",
  },
  resultPopupResetButton: {
    backgroundColor: "#9e35e5",
    shadowColor: "#9e35e5",
  },
  resultPopupResetButtonText: {
    color: "#ffffff",
    fontSize: 16,
    fontWeight: "600",
  },
  // Bottom Result Row Styles
  bottomResultContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingVertical: 15,
    paddingBottom: 10,
    backgroundColor: "#f8f4ff",
  },
  bottomResultContent: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    marginRight: 15,
  },
  bottomResultLabel: {
    fontSize: 16,
    fontWeight: "600",
    color: "#9e35e5",
    marginRight: 8,
  },
  bottomResultText: {
    fontSize: 16,
    fontWeight: "700",
    color: "#6b46c1",
    flex: 1,
  },
  bottomResetButton: {
    backgroundColor: "#9e35e5",
    borderRadius: 20,
    paddingVertical: 10,
    paddingHorizontal: 20,
    shadowColor: "#9e35e5",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 3,
  },
  bottomResetButtonText: {
    color: "#ffffff",
    fontSize: 14,
    fontWeight: "700",
  },
});
