import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#f8f4ff", // 淺紫色背景
  },
  keyboardAvoidingView: {
    flex: 1,
  },
  scrollContainer: {
    flexGrow: 1,
    padding: 20,
    paddingTop: 10, // 減少頂部間距，因為 header 現在是固定的
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingVertical: 16,
    paddingTop: 20, // 給狀態欄留空間
    backgroundColor: "#f8f4ff", // 與背景色一致
    borderBottomWidth: 1,
    borderBottomColor: "rgba(158, 53, 229, 0.15)",
    shadowColor: "#9e35e5",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 4,
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "rgba(158, 53, 229, 0.1)",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(158, 53, 229, 0.2)",
  },
  backButtonText: {
    color: "#9e35e5",
    fontSize: 18,
    fontWeight: "700",
    marginLeft: -1, // 微調箭頭位置
  },
  title: {
    fontSize: 20,
    fontWeight: "700",
    color: "#9e35e5",
    textAlign: "center",
    flex: 1,
    marginHorizontal: 16,
  },
  headerRightSpace: {
    width: 40, // 與 backButton 同寬，保持平衡
  },
  titleContainer: {
    flex: 1,
    alignItems: "center",
  },
  subtitle: {
    fontSize: 12,
    color: "#9e35e5",
    opacity: 0.7,
    marginTop: 2,
    fontWeight: "500",
  },
  topicPreview: {
    fontSize: 14,
    color: "#6b46c1",
    textAlign: "center",
    fontStyle: "italic",
    marginTop: 5,
  },
  optionsCount: {
    fontSize: 14,
    color: "#9e35e5",
    fontWeight: "600",
    textAlign: "center",
    marginTop: 10,
  },
  hint: {
    fontSize: 14,
    color: "#6b7280",
    textAlign: "center",
    marginBottom: 15,
    fontStyle: "italic",
  },
  optionRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 12,
    gap: 10,
  },
  optionsInput: {
    backgroundColor: "#ffffff",
    borderWidth: 2,
    borderColor: "#d1d5db",
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 12,
    fontSize: 16,
    color: "#1f2937",
    shadowColor: "#9e35e5",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  removeButton: {
    backgroundColor: "#ef4444",
    borderRadius: 20,
    width: 36,
    height: 36,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#ef4444",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
    elevation: 2,
  },
  removeButtonText: {
    color: "#ffffff",
    fontSize: 16,
    fontWeight: "bold",
  },
  addButton: {
    backgroundColor: "#9e35e5",
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 20,
    alignItems: "center",
    marginTop: 10,
    shadowColor: "#9e35e5",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.2,
    shadowRadius: 5,
    elevation: 3,
  },
  addButtonText: {
    color: "#ffffff",
    fontSize: 16,
    fontWeight: "600",
  },
  presetOptionsContainer: {
    marginTop: 30,
    backgroundColor: "#ffffff",
    borderRadius: 16,
    padding: 20,
    shadowColor: "#9e35e5",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 3,
  },
  presetOptionsTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: "#9e35e5",
    marginBottom: 8,
  },
  presetOptionsHint: {
    fontSize: 14,
    color: "#6b7280",
    marginBottom: 15,
  },
  presetOptionsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  presetOptionTag: {
    backgroundColor: "#f3f4f6",
    borderRadius: 20,
    paddingHorizontal: 16,
    paddingVertical: 8,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: "#e5e7eb",
  },
  presetOptionText: {
    color: "#374151",
    fontSize: 14,
    fontWeight: "500",
  },
  presetOptionTextActive: {
    color: "#9e35e5",
    fontWeight: "600",
  },
  resultContainer: {
    marginTop: 30,
    backgroundColor: "#ffffff",
    borderRadius: 20,
    padding: 25,
    shadowColor: "#9e35e5",
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 5,
    borderWidth: 2,
    borderColor: "#9e35e5",
    alignItems: "center",
  },

  resultTitle: {
    fontSize: 20,
    fontWeight: "700",
    color: "#9e35e5",
    marginBottom: 20,
    textAlign: "center",
  },

  resultBox: {
    backgroundColor: "#f8f5ff",
    borderRadius: 16,
    paddingVertical: 20,
    paddingHorizontal: 30,
    marginBottom: 25,
    borderWidth: 2,
    borderColor: "#e0d4f7",
    minWidth: "80%",
    alignItems: "center",
  },

  resultText: {
    fontSize: 24,
    fontWeight: "600",
    color: "#6b46c1",
    textAlign: "center",
    letterSpacing: 0.5,
  },

  resetButton: {
    backgroundColor: "#9e35e5",
    borderRadius: 25,
    paddingVertical: 12,
    paddingHorizontal: 30,
    shadowColor: "#9e35e5",
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 4,
  },

  resetButtonText: {
    color: "#ffffff",
    fontSize: 16,
    fontWeight: "600",
    textAlign: "center",
  },
  // 新增的樣式
  topicSection: {
    marginBottom: 20,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: "#9e35e5",
    marginBottom: 12,
    textAlign: "left",
  },
  // 新的選項樣式
  optionItemRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 12,
    backgroundColor: "#ffffff",
    borderRadius: 12,
    padding: 4,
    shadowColor: "#9e35e5",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  optionNumberContainer: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: "#9e35e5",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
  },
  optionNumber: {
    color: "#ffffff",
    fontSize: 14,
    fontWeight: "600",
  },
  optionInput: {
    flex: 1,
    fontSize: 16,
    color: "#343a40",
    paddingVertical: 12,
    paddingHorizontal: 0,
    minHeight: 44,
  },
  removeOptionButton: {
    width: 32,
    height: 32,
    alignItems: "center",
    justifyContent: "center",
    marginLeft: 8,
  },
  removeOptionText: {
    fontSize: 16,
  },
  addOptionButton: {
    backgroundColor: "#f3f4f6",
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 16,
    marginTop: 8,
    borderWidth: 2,
    borderColor: "#e5e7eb",
    borderStyle: "dashed",
    alignItems: "center",
  },
  addOptionText: {
    color: "#9e35e5",
    fontSize: 16,
    fontWeight: "500",
  },
  // 新的選項按鈕樣式
  optionsSection: {
    marginBottom: 20,
  },
  optionsButton: {
    backgroundColor: "#ffffff",
    borderRadius: 16,
    padding: 20,
    shadowColor: "#9e35e5",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 3,
    borderWidth: 1,
    borderColor: "#e5e7eb",
  },
  optionsButtonContent: {
    flexDirection: "row",
    alignItems: "center",
  },
  optionsButtonIcon: {
    fontSize: 24,
    marginRight: 16,
  },
  optionsButtonTextContainer: {
    flex: 1,
  },
  optionsButtonTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: "#9e35e5",
    marginBottom: 4,
  },
  optionsButtonSubtitle: {
    fontSize: 14,
    color: "#6b7280",
  },
  optionsButtonArrow: {
    fontSize: 24,
    color: "#9e35e5",
    fontWeight: "300",
  },
  // 輪盤占位符樣式
  wheelPlaceholder: {
    backgroundColor: "#ffffff",
    borderRadius: 16,
    padding: 40,
    marginBottom: 20,
    alignItems: "center",
    shadowColor: "#9e35e5",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
    borderWidth: 2,
    borderColor: "#f3f4f6",
    borderStyle: "dashed",
  },
  wheelPlaceholderText: {
    fontSize: 18,
    fontWeight: "600",
    color: "#9e35e5",
    textAlign: "center",
    marginBottom: 8,
  },
  wheelPlaceholderHint: {
    fontSize: 14,
    color: "#6b7280",
    textAlign: "center",
    lineHeight: 20,
  },
});
